//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserve__a_Five_a_Side_Football.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Reserve_a_Five_a_SideEntities : DbContext
    {
        public Reserve_a_Five_a_SideEntities()
            : base("name=Reserve_a_Five_a_SideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Legaue> Legaues { get; set; }
        public virtual DbSet<Ownar> Ownars { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Stadium> Stadium { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<LeagueMessage> LeagueMessages { get; set; }
        public virtual DbSet<ReservationMessage> ReservationMessages { get; set; }
    
        public virtual ObjectResult<GetTeamDetails_Result> GetTeamDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamDetails_Result>("GetTeamDetails");
        }
    
        public virtual ObjectResult<GetTeamsData_Result> GetTeamsData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeamsData_Result>("GetTeamsData");
        }
    
        public virtual ObjectResult<Team_DetailsForUserCaptin_Result> Team_DetailsForUserCaptin(Nullable<int> captinID)
        {
            var captinIDParameter = captinID.HasValue ?
                new ObjectParameter("CaptinID", captinID) :
                new ObjectParameter("CaptinID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Team_DetailsForUserCaptin_Result>("Team_DetailsForUserCaptin", captinIDParameter);
        }
    }
}
