//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserve__a_Five_a_Side_Football.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legaue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Legaue()
        {
            this.Teams = new HashSet<Team>();
            this.LeagueMessages = new HashSet<LeagueMessage>();
        }
    
        public int LegueID { get; set; }
        public string Legue_Name { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int StadiumID { get; set; }
        public string StadiumName { get; set; }
        public System.DateTime EndReg { get; set; }
        public string Reward { get; set; }
        public string City { get; set; }
        public System.TimeSpan TimePlay { get; set; }
        public Nullable<int> NumberOfSubscribersInlegaue { get; set; }
        public int CurrentSubscriberslegaue { get; set; }
    
        public virtual Stadium Stadium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeagueMessage> LeagueMessages { get; set; }
    }
}
