//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserve__a_Five_a_Side_Football.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationMessage
    {
        public int MessageID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string MessageContent { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
