//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserve__a_Five_a_Side_Football.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int CaptainID { get; set; }
        public string NationalID_Player1 { get; set; }
        public string NationalID_Player2 { get; set; }
        public string NationalID_Player3 { get; set; }
        public string NationalID_Player4 { get; set; }
        public string NationalID_Player5 { get; set; }
        public int LegueID { get; set; }
    
        public virtual Legaue Legaue { get; set; }
        public virtual Player Player { get; set; }
    }
}
